/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// BackofficeModelAPIWSContactGetUserAcceptanceRequestData
    /// </summary>
    [DataContract]
    public partial class BackofficeModelAPIWSContactGetUserAcceptanceRequestData :  IEquatable<BackofficeModelAPIWSContactGetUserAcceptanceRequestData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackofficeModelAPIWSContactGetUserAcceptanceRequestData" /> class.
        /// </summary>
        /// <param name="contactEmail">contactEmail.</param>
        /// <param name="sourceName">sourceName.</param>
        /// <param name="tokenAPI">tokenAPI.</param>
        public BackofficeModelAPIWSContactGetUserAcceptanceRequestData(string contactEmail = default(string), string sourceName = default(string), string tokenAPI = default(string))
        {
            this.ContactEmail = contactEmail;
            this.SourceName = sourceName;
            this.TokenAPI = tokenAPI;
        }
        
        /// <summary>
        /// Gets or Sets ContactEmail
        /// </summary>
        [DataMember(Name="ContactEmail", EmitDefaultValue=false)]
        public string ContactEmail { get; set; }

        /// <summary>
        /// Gets or Sets SourceName
        /// </summary>
        [DataMember(Name="SourceName", EmitDefaultValue=false)]
        public string SourceName { get; set; }

        /// <summary>
        /// Gets or Sets TokenAPI
        /// </summary>
        [DataMember(Name="TokenAPI", EmitDefaultValue=false)]
        public string TokenAPI { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BackofficeModelAPIWSContactGetUserAcceptanceRequestData {\n");
            sb.Append("  ContactEmail: ").Append(ContactEmail).Append("\n");
            sb.Append("  SourceName: ").Append(SourceName).Append("\n");
            sb.Append("  TokenAPI: ").Append(TokenAPI).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BackofficeModelAPIWSContactGetUserAcceptanceRequestData);
        }

        /// <summary>
        /// Returns true if BackofficeModelAPIWSContactGetUserAcceptanceRequestData instances are equal
        /// </summary>
        /// <param name="input">Instance of BackofficeModelAPIWSContactGetUserAcceptanceRequestData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BackofficeModelAPIWSContactGetUserAcceptanceRequestData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ContactEmail == input.ContactEmail ||
                    (this.ContactEmail != null &&
                    this.ContactEmail.Equals(input.ContactEmail))
                ) && 
                (
                    this.SourceName == input.SourceName ||
                    (this.SourceName != null &&
                    this.SourceName.Equals(input.SourceName))
                ) && 
                (
                    this.TokenAPI == input.TokenAPI ||
                    (this.TokenAPI != null &&
                    this.TokenAPI.Equals(input.TokenAPI))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ContactEmail != null)
                    hashCode = hashCode * 59 + this.ContactEmail.GetHashCode();
                if (this.SourceName != null)
                    hashCode = hashCode * 59 + this.SourceName.GetHashCode();
                if (this.TokenAPI != null)
                    hashCode = hashCode * 59 + this.TokenAPI.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
