/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// BackofficeModelSorgentiIndexMaskModel
    /// </summary>
    [DataContract]
    public partial class BackofficeModelSorgentiIndexMaskModel :  IEquatable<BackofficeModelSorgentiIndexMaskModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackofficeModelSorgentiIndexMaskModel" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="elencoTitle">elencoTitle.</param>
        /// <param name="goBackLink">goBackLink.</param>
        public BackofficeModelSorgentiIndexMaskModel(int? id = default(int?), string elencoTitle = default(string), string goBackLink = default(string))
        {
            this.Id = id;
            this.ElencoTitle = elencoTitle;
            this.GoBackLink = goBackLink;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets ElencoTitle
        /// </summary>
        [DataMember(Name="ElencoTitle", EmitDefaultValue=false)]
        public string ElencoTitle { get; set; }

        /// <summary>
        /// Gets or Sets GoBackLink
        /// </summary>
        [DataMember(Name="goBackLink", EmitDefaultValue=false)]
        public string GoBackLink { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BackofficeModelSorgentiIndexMaskModel {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ElencoTitle: ").Append(ElencoTitle).Append("\n");
            sb.Append("  GoBackLink: ").Append(GoBackLink).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BackofficeModelSorgentiIndexMaskModel);
        }

        /// <summary>
        /// Returns true if BackofficeModelSorgentiIndexMaskModel instances are equal
        /// </summary>
        /// <param name="input">Instance of BackofficeModelSorgentiIndexMaskModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BackofficeModelSorgentiIndexMaskModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ElencoTitle == input.ElencoTitle ||
                    (this.ElencoTitle != null &&
                    this.ElencoTitle.Equals(input.ElencoTitle))
                ) && 
                (
                    this.GoBackLink == input.GoBackLink ||
                    (this.GoBackLink != null &&
                    this.GoBackLink.Equals(input.GoBackLink))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.ElencoTitle != null)
                    hashCode = hashCode * 59 + this.ElencoTitle.GetHashCode();
                if (this.GoBackLink != null)
                    hashCode = hashCode * 59 + this.GoBackLink.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
