/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ModelLayerBackDatatableResponseColumn
    /// </summary>
    [DataContract]
    public partial class ModelLayerBackDatatableResponseColumn :  IEquatable<ModelLayerBackDatatableResponseColumn>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModelLayerBackDatatableResponseColumn" /> class.
        /// </summary>
        /// <param name="data">data.</param>
        /// <param name="name">name.</param>
        /// <param name="searchable">searchable.</param>
        /// <param name="orderable">orderable.</param>
        /// <param name="search">search.</param>
        public ModelLayerBackDatatableResponseColumn(string data = default(string), string name = default(string), bool? searchable = default(bool?), bool? orderable = default(bool?), ModelLayerBackDatatableResponseSearch search = default(ModelLayerBackDatatableResponseSearch))
        {
            this.Data = data;
            this.Name = name;
            this.Searchable = searchable;
            this.Orderable = orderable;
            this.Search = search;
        }
        
        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public string Data { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Searchable
        /// </summary>
        [DataMember(Name="searchable", EmitDefaultValue=false)]
        public bool? Searchable { get; set; }

        /// <summary>
        /// Gets or Sets Orderable
        /// </summary>
        [DataMember(Name="orderable", EmitDefaultValue=false)]
        public bool? Orderable { get; set; }

        /// <summary>
        /// Gets or Sets Search
        /// </summary>
        [DataMember(Name="search", EmitDefaultValue=false)]
        public ModelLayerBackDatatableResponseSearch Search { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModelLayerBackDatatableResponseColumn {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Searchable: ").Append(Searchable).Append("\n");
            sb.Append("  Orderable: ").Append(Orderable).Append("\n");
            sb.Append("  Search: ").Append(Search).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModelLayerBackDatatableResponseColumn);
        }

        /// <summary>
        /// Returns true if ModelLayerBackDatatableResponseColumn instances are equal
        /// </summary>
        /// <param name="input">Instance of ModelLayerBackDatatableResponseColumn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModelLayerBackDatatableResponseColumn input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Data == input.Data ||
                    (this.Data != null &&
                    this.Data.Equals(input.Data))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Searchable == input.Searchable ||
                    (this.Searchable != null &&
                    this.Searchable.Equals(input.Searchable))
                ) && 
                (
                    this.Orderable == input.Orderable ||
                    (this.Orderable != null &&
                    this.Orderable.Equals(input.Orderable))
                ) && 
                (
                    this.Search == input.Search ||
                    (this.Search != null &&
                    this.Search.Equals(input.Search))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Data != null)
                    hashCode = hashCode * 59 + this.Data.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Searchable != null)
                    hashCode = hashCode * 59 + this.Searchable.GetHashCode();
                if (this.Orderable != null)
                    hashCode = hashCode * 59 + this.Orderable.GetHashCode();
                if (this.Search != null)
                    hashCode = hashCode * 59 + this.Search.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
