/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIWSContactGetUserAcceptanceRequestData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIWSContactGetUserAcceptanceRequestDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIWSContactGetUserAcceptanceRequestData
        //private BackofficeModelAPIWSContactGetUserAcceptanceRequestData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIWSContactGetUserAcceptanceRequestData
            //instance = new BackofficeModelAPIWSContactGetUserAcceptanceRequestData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIWSContactGetUserAcceptanceRequestData
        /// </summary>
        [Test]
        public void BackofficeModelAPIWSContactGetUserAcceptanceRequestDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIWSContactGetUserAcceptanceRequestData
            //Assert.IsInstanceOfType<BackofficeModelAPIWSContactGetUserAcceptanceRequestData> (instance, "variable 'instance' is a BackofficeModelAPIWSContactGetUserAcceptanceRequestData");
        }


        /// <summary>
        /// Test the property 'ContactEmail'
        /// </summary>
        [Test]
        public void ContactEmailTest()
        {
            // TODO unit test for the property 'ContactEmail'
        }
        /// <summary>
        /// Test the property 'SourceName'
        /// </summary>
        [Test]
        public void SourceNameTest()
        {
            // TODO unit test for the property 'SourceName'
        }
        /// <summary>
        /// Test the property 'TokenAPI'
        /// </summary>
        [Test]
        public void TokenAPITest()
        {
            // TODO unit test for the property 'TokenAPI'
        }

    }

}
