/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIPolicyGetPolicyResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIPolicyGetPolicyResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIPolicyGetPolicyResponseData
        //private BackofficeModelAPIPolicyGetPolicyResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIPolicyGetPolicyResponseData
            //instance = new BackofficeModelAPIPolicyGetPolicyResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIPolicyGetPolicyResponseData
        /// </summary>
        [Test]
        public void BackofficeModelAPIPolicyGetPolicyResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIPolicyGetPolicyResponseData
            //Assert.IsInstanceOfType<BackofficeModelAPIPolicyGetPolicyResponseData> (instance, "variable 'instance' is a BackofficeModelAPIPolicyGetPolicyResponseData");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
