/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIWSContactAddRequestAccettazioniData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIWSContactAddRequestAccettazioniDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIWSContactAddRequestAccettazioniData
        //private BackofficeModelAPIWSContactAddRequestAccettazioniData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIWSContactAddRequestAccettazioniData
            //instance = new BackofficeModelAPIWSContactAddRequestAccettazioniData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIWSContactAddRequestAccettazioniData
        /// </summary>
        [Test]
        public void BackofficeModelAPIWSContactAddRequestAccettazioniDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIWSContactAddRequestAccettazioniData
            //Assert.IsInstanceOfType<BackofficeModelAPIWSContactAddRequestAccettazioniData> (instance, "variable 'instance' is a BackofficeModelAPIWSContactAddRequestAccettazioniData");
        }


        /// <summary>
        /// Test the property 'CheckData'
        /// </summary>
        [Test]
        public void CheckDataTest()
        {
            // TODO unit test for the property 'CheckData'
        }

    }

}
