/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIWSContactAddRequestSearchIdDataItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIWSContactAddRequestSearchIdDataItemTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIWSContactAddRequestSearchIdDataItem
        //private BackofficeModelAPIWSContactAddRequestSearchIdDataItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIWSContactAddRequestSearchIdDataItem
            //instance = new BackofficeModelAPIWSContactAddRequestSearchIdDataItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIWSContactAddRequestSearchIdDataItem
        /// </summary>
        [Test]
        public void BackofficeModelAPIWSContactAddRequestSearchIdDataItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIWSContactAddRequestSearchIdDataItem
            //Assert.IsInstanceOfType<BackofficeModelAPIWSContactAddRequestSearchIdDataItem> (instance, "variable 'instance' is a BackofficeModelAPIWSContactAddRequestSearchIdDataItem");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
