/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData
        //private BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData
            //instance = new BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData
        /// </summary>
        [Test]
        public void BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData
            //Assert.IsInstanceOfType<BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData> (instance, "variable 'instance' is a BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData");
        }


        /// <summary>
        /// Test the property 'Contatto'
        /// </summary>
        [Test]
        public void ContattoTest()
        {
            // TODO unit test for the property 'Contatto'
        }
        /// <summary>
        /// Test the property 'Guid'
        /// </summary>
        [Test]
        public void GuidTest()
        {
            // TODO unit test for the property 'Guid'
        }
        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Test]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
        /// <summary>
        /// Test the property 'TokenAPI'
        /// </summary>
        [Test]
        public void TokenAPITest()
        {
            // TODO unit test for the property 'TokenAPI'
        }

    }

}
