/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIPolicySavePolicyRequestData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIPolicySavePolicyRequestDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIPolicySavePolicyRequestData
        //private BackofficeModelAPIPolicySavePolicyRequestData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIPolicySavePolicyRequestData
            //instance = new BackofficeModelAPIPolicySavePolicyRequestData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIPolicySavePolicyRequestData
        /// </summary>
        [Test]
        public void BackofficeModelAPIPolicySavePolicyRequestDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIPolicySavePolicyRequestData
            //Assert.IsInstanceOfType<BackofficeModelAPIPolicySavePolicyRequestData> (instance, "variable 'instance' is a BackofficeModelAPIPolicySavePolicyRequestData");
        }


        /// <summary>
        /// Test the property 'TypeId'
        /// </summary>
        [Test]
        public void TypeIdTest()
        {
            // TODO unit test for the property 'TypeId'
        }
        /// <summary>
        /// Test the property 'LinguaId'
        /// </summary>
        [Test]
        public void LinguaIdTest()
        {
            // TODO unit test for the property 'LinguaId'
        }
        /// <summary>
        /// Test the property 'SorgenteId'
        /// </summary>
        [Test]
        public void SorgenteIdTest()
        {
            // TODO unit test for the property 'SorgenteId'
        }
        /// <summary>
        /// Test the property 'ClienteId'
        /// </summary>
        [Test]
        public void ClienteIdTest()
        {
            // TODO unit test for the property 'ClienteId'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Titolo'
        /// </summary>
        [Test]
        public void TitoloTest()
        {
            // TODO unit test for the property 'Titolo'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
