/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIWSContactAddRequestRequestData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIWSContactAddRequestRequestDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIWSContactAddRequestRequestData
        //private BackofficeModelAPIWSContactAddRequestRequestData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIWSContactAddRequestRequestData
            //instance = new BackofficeModelAPIWSContactAddRequestRequestData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIWSContactAddRequestRequestData
        /// </summary>
        [Test]
        public void BackofficeModelAPIWSContactAddRequestRequestDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIWSContactAddRequestRequestData
            //Assert.IsInstanceOfType<BackofficeModelAPIWSContactAddRequestRequestData> (instance, "variable 'instance' is a BackofficeModelAPIWSContactAddRequestRequestData");
        }


        /// <summary>
        /// Test the property 'Contatto'
        /// </summary>
        [Test]
        public void ContattoTest()
        {
            // TODO unit test for the property 'Contatto'
        }
        /// <summary>
        /// Test the property 'SourceName'
        /// </summary>
        [Test]
        public void SourceNameTest()
        {
            // TODO unit test for the property 'SourceName'
        }
        /// <summary>
        /// Test the property 'SearchIds'
        /// </summary>
        [Test]
        public void SearchIdsTest()
        {
            // TODO unit test for the property 'SearchIds'
        }
        /// <summary>
        /// Test the property 'Richiesta'
        /// </summary>
        [Test]
        public void RichiestaTest()
        {
            // TODO unit test for the property 'Richiesta'
        }
        /// <summary>
        /// Test the property 'Accettazioni'
        /// </summary>
        [Test]
        public void AccettazioniTest()
        {
            // TODO unit test for the property 'Accettazioni'
        }
        /// <summary>
        /// Test the property 'TokenAPI'
        /// </summary>
        [Test]
        public void TokenAPITest()
        {
            // TODO unit test for the property 'TokenAPI'
        }

    }

}
