/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPIWSContactAddRequestSearchIdsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPIWSContactAddRequestSearchIdsDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPIWSContactAddRequestSearchIdsData
        //private BackofficeModelAPIWSContactAddRequestSearchIdsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPIWSContactAddRequestSearchIdsData
            //instance = new BackofficeModelAPIWSContactAddRequestSearchIdsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPIWSContactAddRequestSearchIdsData
        /// </summary>
        [Test]
        public void BackofficeModelAPIWSContactAddRequestSearchIdsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPIWSContactAddRequestSearchIdsData
            //Assert.IsInstanceOfType<BackofficeModelAPIWSContactAddRequestSearchIdsData> (instance, "variable 'instance' is a BackofficeModelAPIWSContactAddRequestSearchIdsData");
        }


        /// <summary>
        /// Test the property 'SearchData'
        /// </summary>
        [Test]
        public void SearchDataTest()
        {
            // TODO unit test for the property 'SearchData'
        }

    }

}
