/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelWSAPIHooksHandlerMailupData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelWSAPIHooksHandlerMailupDataTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelWSAPIHooksHandlerMailupData
        //private BackofficeModelWSAPIHooksHandlerMailupData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelWSAPIHooksHandlerMailupData
            //instance = new BackofficeModelWSAPIHooksHandlerMailupData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelWSAPIHooksHandlerMailupData
        /// </summary>
        [Test]
        public void BackofficeModelWSAPIHooksHandlerMailupDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelWSAPIHooksHandlerMailupData
            //Assert.IsInstanceOfType<BackofficeModelWSAPIHooksHandlerMailupData> (instance, "variable 'instance' is a BackofficeModelWSAPIHooksHandlerMailupData");
        }


        /// <summary>
        /// Test the property 'IdConsole'
        /// </summary>
        [Test]
        public void IdConsoleTest()
        {
            // TODO unit test for the property 'IdConsole'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Test]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'IdList'
        /// </summary>
        [Test]
        public void IdListTest()
        {
            // TODO unit test for the property 'IdList'
        }
        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Test]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Test]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }
        /// <summary>
        /// Test the property 'Sorgente'
        /// </summary>
        [Test]
        public void SorgenteTest()
        {
            // TODO unit test for the property 'Sorgente'
        }
        /// <summary>
        /// Test the property 'SorgenteSysName'
        /// </summary>
        [Test]
        public void SorgenteSysNameTest()
        {
            // TODO unit test for the property 'SorgenteSysName'
        }

    }

}
