/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelSorgentiIndexMaskModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelSorgentiIndexMaskModelTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelSorgentiIndexMaskModel
        //private BackofficeModelSorgentiIndexMaskModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelSorgentiIndexMaskModel
            //instance = new BackofficeModelSorgentiIndexMaskModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelSorgentiIndexMaskModel
        /// </summary>
        [Test]
        public void BackofficeModelSorgentiIndexMaskModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelSorgentiIndexMaskModel
            //Assert.IsInstanceOfType<BackofficeModelSorgentiIndexMaskModel> (instance, "variable 'instance' is a BackofficeModelSorgentiIndexMaskModel");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ElencoTitle'
        /// </summary>
        [Test]
        public void ElencoTitleTest()
        {
            // TODO unit test for the property 'ElencoTitle'
        }
        /// <summary>
        /// Test the property 'GoBackLink'
        /// </summary>
        [Test]
        public void GoBackLinkTest()
        {
            // TODO unit test for the property 'GoBackLink'
        }

    }

}
