/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BackofficeModelAPINewsletterSaveNewsletterRequestItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BackofficeModelAPINewsletterSaveNewsletterRequestItemTests
    {
        // TODO uncomment below to declare an instance variable for BackofficeModelAPINewsletterSaveNewsletterRequestItem
        //private BackofficeModelAPINewsletterSaveNewsletterRequestItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BackofficeModelAPINewsletterSaveNewsletterRequestItem
            //instance = new BackofficeModelAPINewsletterSaveNewsletterRequestItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BackofficeModelAPINewsletterSaveNewsletterRequestItem
        /// </summary>
        [Test]
        public void BackofficeModelAPINewsletterSaveNewsletterRequestItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BackofficeModelAPINewsletterSaveNewsletterRequestItem
            //Assert.IsInstanceOfType<BackofficeModelAPINewsletterSaveNewsletterRequestItem> (instance, "variable 'instance' is a BackofficeModelAPINewsletterSaveNewsletterRequestItem");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'TypeId'
        /// </summary>
        [Test]
        public void TypeIdTest()
        {
            // TODO unit test for the property 'TypeId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ExportPar'
        /// </summary>
        [Test]
        public void ExportParTest()
        {
            // TODO unit test for the property 'ExportPar'
        }
        /// <summary>
        /// Test the property 'SearchPar'
        /// </summary>
        [Test]
        public void SearchParTest()
        {
            // TODO unit test for the property 'SearchPar'
        }
        /// <summary>
        /// Test the property 'IsExportEnabled'
        /// </summary>
        [Test]
        public void IsExportEnabledTest()
        {
            // TODO unit test for the property 'IsExportEnabled'
        }

    }

}
