/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelLayerNewsletterMailUpSearchParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelLayerNewsletterMailUpSearchParameterTests
    {
        // TODO uncomment below to declare an instance variable for ModelLayerNewsletterMailUpSearchParameter
        //private ModelLayerNewsletterMailUpSearchParameter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelLayerNewsletterMailUpSearchParameter
            //instance = new ModelLayerNewsletterMailUpSearchParameter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelLayerNewsletterMailUpSearchParameter
        /// </summary>
        [Test]
        public void ModelLayerNewsletterMailUpSearchParameterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelLayerNewsletterMailUpSearchParameter
            //Assert.IsInstanceOfType<ModelLayerNewsletterMailUpSearchParameter> (instance, "variable 'instance' is a ModelLayerNewsletterMailUpSearchParameter");
        }


        /// <summary>
        /// Test the property 'SearchId'
        /// </summary>
        [Test]
        public void SearchIdTest()
        {
            // TODO unit test for the property 'SearchId'
        }

    }

}
