/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelLayerNewsletterMailUpExportParameter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelLayerNewsletterMailUpExportParameterTests
    {
        // TODO uncomment below to declare an instance variable for ModelLayerNewsletterMailUpExportParameter
        //private ModelLayerNewsletterMailUpExportParameter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelLayerNewsletterMailUpExportParameter
            //instance = new ModelLayerNewsletterMailUpExportParameter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelLayerNewsletterMailUpExportParameter
        /// </summary>
        [Test]
        public void ModelLayerNewsletterMailUpExportParameterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelLayerNewsletterMailUpExportParameter
            //Assert.IsInstanceOfType<ModelLayerNewsletterMailUpExportParameter> (instance, "variable 'instance' is a ModelLayerNewsletterMailUpExportParameter");
        }


        /// <summary>
        /// Test the property 'ListId'
        /// </summary>
        [Test]
        public void ListIdTest()
        {
            // TODO unit test for the property 'ListId'
        }
        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Test]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
        /// <summary>
        /// Test the property 'Confirm'
        /// </summary>
        [Test]
        public void ConfirmTest()
        {
            // TODO unit test for the property 'Confirm'
        }
        /// <summary>
        /// Test the property 'ReturnCode'
        /// </summary>
        [Test]
        public void ReturnCodeTest()
        {
            // TODO unit test for the property 'ReturnCode'
        }
        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [Test]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }
        /// <summary>
        /// Test the property 'ListGuid'
        /// </summary>
        [Test]
        public void ListGuidTest()
        {
            // TODO unit test for the property 'ListGuid'
        }

    }

}
