/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelLayerBackDatatableResponseColumn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelLayerBackDatatableResponseColumnTests
    {
        // TODO uncomment below to declare an instance variable for ModelLayerBackDatatableResponseColumn
        //private ModelLayerBackDatatableResponseColumn instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelLayerBackDatatableResponseColumn
            //instance = new ModelLayerBackDatatableResponseColumn();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelLayerBackDatatableResponseColumn
        /// </summary>
        [Test]
        public void ModelLayerBackDatatableResponseColumnInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelLayerBackDatatableResponseColumn
            //Assert.IsInstanceOfType<ModelLayerBackDatatableResponseColumn> (instance, "variable 'instance' is a ModelLayerBackDatatableResponseColumn");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Searchable'
        /// </summary>
        [Test]
        public void SearchableTest()
        {
            // TODO unit test for the property 'Searchable'
        }
        /// <summary>
        /// Test the property 'Orderable'
        /// </summary>
        [Test]
        public void OrderableTest()
        {
            // TODO unit test for the property 'Orderable'
        }
        /// <summary>
        /// Test the property 'Search'
        /// </summary>
        [Test]
        public void SearchTest()
        {
            // TODO unit test for the property 'Search'
        }

    }

}
