/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ModelLayerBackDatatableResponseOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ModelLayerBackDatatableResponseOrderTests
    {
        // TODO uncomment below to declare an instance variable for ModelLayerBackDatatableResponseOrder
        //private ModelLayerBackDatatableResponseOrder instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ModelLayerBackDatatableResponseOrder
            //instance = new ModelLayerBackDatatableResponseOrder();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ModelLayerBackDatatableResponseOrder
        /// </summary>
        [Test]
        public void ModelLayerBackDatatableResponseOrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ModelLayerBackDatatableResponseOrder
            //Assert.IsInstanceOfType<ModelLayerBackDatatableResponseOrder> (instance, "variable 'instance' is a ModelLayerBackDatatableResponseOrder");
        }


        /// <summary>
        /// Test the property 'Column'
        /// </summary>
        [Test]
        public void ColumnTest()
        {
            // TODO unit test for the property 'Column'
        }
        /// <summary>
        /// Test the property 'Dir'
        /// </summary>
        [Test]
        public void DirTest()
        {
            // TODO unit test for the property 'Dir'
        }

    }

}
