/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccettazioniStoricoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AccettazioniStoricoApiTests
    {
        private AccettazioniStoricoApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccettazioniStoricoApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccettazioniStoricoApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AccettazioniStoricoApi
            //Assert.IsInstanceOfType(typeof(AccettazioniStoricoApi), instance, "instance is a AccettazioniStoricoApi");
        }

        
        /// <summary>
        /// Test AccettazioniStoricoGetList
        /// </summary>
        [Test]
        public void AccettazioniStoricoGetListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.AccettazioniStoricoGetList();
            //Assert.IsInstanceOf<BackofficeModelAPICommonDataSourceResult> (response, "response is BackofficeModelAPICommonDataSourceResult");
        }
        
        /// <summary>
        /// Test AccettazioniStoricoLockAccountCredential
        /// </summary>
        [Test]
        public void AccettazioniStoricoLockAccountCredentialTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? utenteId = null;
            //var response = instance.AccettazioniStoricoLockAccountCredential(utenteId);
            //Assert.IsInstanceOf<BackofficeModelAPICommonMessageModel> (response, "response is BackofficeModelAPICommonMessageModel");
        }
        
        /// <summary>
        /// Test AccettazioniStoricoSendAccountCredential
        /// </summary>
        [Test]
        public void AccettazioniStoricoSendAccountCredentialTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? utenteId = null;
            //var response = instance.AccettazioniStoricoSendAccountCredential(utenteId);
            //Assert.IsInstanceOf<BackofficeModelAPICommonMessageModel> (response, "response is BackofficeModelAPICommonMessageModel");
        }
        
        /// <summary>
        /// Test AccettazioniStoricoUnlockAccountCredential
        /// </summary>
        [Test]
        public void AccettazioniStoricoUnlockAccountCredentialTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? utenteId = null;
            //var response = instance.AccettazioniStoricoUnlockAccountCredential(utenteId);
            //Assert.IsInstanceOf<BackofficeModelAPICommonMessageModel> (response, "response is BackofficeModelAPICommonMessageModel");
        }
        
    }

}
