/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NewsletterApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NewsletterApiTests
    {
        private NewsletterApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NewsletterApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewsletterApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NewsletterApi
            //Assert.IsInstanceOfType(typeof(NewsletterApi), instance, "instance is a NewsletterApi");
        }

        
        /// <summary>
        /// Test NewsletterGetNewsletters
        /// </summary>
        [Test]
        public void NewsletterGetNewslettersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPINewsletterGetNewslettersRequestData oRequest = null;
            //var response = instance.NewsletterGetNewsletters(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPINewsletterGetNewslettersResponseData> (response, "response is BackofficeModelAPINewsletterGetNewslettersResponseData");
        }
        
        /// <summary>
        /// Test NewsletterSaveNewsletters
        /// </summary>
        [Test]
        public void NewsletterSaveNewslettersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest = null;
            //var response = instance.NewsletterSaveNewsletters(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPINewsletterSaveNewsletterResponseData> (response, "response is BackofficeModelAPINewsletterSaveNewsletterResponseData");
        }
        
    }

}
