/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PolicyApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PolicyApiTests
    {
        private PolicyApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PolicyApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PolicyApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PolicyApi
            //Assert.IsInstanceOfType(typeof(PolicyApi), instance, "instance is a PolicyApi");
        }

        
        /// <summary>
        /// Test PolicyGetPolicy
        /// </summary>
        [Test]
        public void PolicyGetPolicyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIPolicyGetPolicyRequestData oRequest = null;
            //var response = instance.PolicyGetPolicy(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIPolicyGetPolicyResponseData> (response, "response is BackofficeModelAPIPolicyGetPolicyResponseData");
        }
        
        /// <summary>
        /// Test PolicySavePolicy
        /// </summary>
        [Test]
        public void PolicySavePolicyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIPolicySavePolicyRequestData oRequest = null;
            //var response = instance.PolicySavePolicy(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPICommonMessageModel> (response, "response is BackofficeModelAPICommonMessageModel");
        }
        
    }

}
