/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UtentiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UtentiApiTests
    {
        private UtentiApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UtentiApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UtentiApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UtentiApi
            //Assert.IsInstanceOfType(typeof(UtentiApi), instance, "instance is a UtentiApi");
        }

        
        /// <summary>
        /// Test UtentiGetList
        /// </summary>
        [Test]
        public void UtentiGetListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.UtentiGetList();
            //Assert.IsInstanceOf<BackofficeModelAPICommonDataSourceResult> (response, "response is BackofficeModelAPICommonDataSourceResult");
        }
        
        /// <summary>
        /// Test UtentiLockAccountCredential
        /// </summary>
        [Test]
        public void UtentiLockAccountCredentialTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? utenteId = null;
            //var response = instance.UtentiLockAccountCredential(utenteId);
            //Assert.IsInstanceOf<BackofficeModelAPICommonMessageModel> (response, "response is BackofficeModelAPICommonMessageModel");
        }
        
        /// <summary>
        /// Test UtentiSendAccountCredential
        /// </summary>
        [Test]
        public void UtentiSendAccountCredentialTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? utenteId = null;
            //var response = instance.UtentiSendAccountCredential(utenteId);
            //Assert.IsInstanceOf<BackofficeModelAPICommonMessageModel> (response, "response is BackofficeModelAPICommonMessageModel");
        }
        
        /// <summary>
        /// Test UtentiUnlockAccountCredential
        /// </summary>
        [Test]
        public void UtentiUnlockAccountCredentialTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? utenteId = null;
            //var response = instance.UtentiUnlockAccountCredential(utenteId);
            //Assert.IsInstanceOf<BackofficeModelAPICommonMessageModel> (response, "response is BackofficeModelAPICommonMessageModel");
        }
        
    }

}
