/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.trackoApiClient;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WSApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WSApiTests
    {
        private WSApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WSApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WSApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WSApi
            //Assert.IsInstanceOfType(typeof(WSApi), instance, "instance is a WSApi");
        }

        
        /// <summary>
        /// Test WSAddRequest
        /// </summary>
        [Test]
        public void WSAddRequestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIWSContactAddRequestRequestData oRequest = null;
            //var response = instance.WSAddRequest(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIWSContactAddRequestResponseData> (response, "response is BackofficeModelAPIWSContactAddRequestResponseData");
        }
        
        /// <summary>
        /// Test WSCheckPrivacyPolicyChanged
        /// </summary>
        [Test]
        public void WSCheckPrivacyPolicyChangedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIWSPolicyCheckPrivacyPolicyChangedRequestData oRequest = null;
            //var response = instance.WSCheckPrivacyPolicyChanged(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIWSPolicyCheckPrivacyPolicyChangedResponseData> (response, "response is BackofficeModelAPIWSPolicyCheckPrivacyPolicyChangedResponseData");
        }
        
        /// <summary>
        /// Test WSGetPolicy
        /// </summary>
        [Test]
        public void WSGetPolicyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIWSPolicyGetPolicyRequestData oRequest = null;
            //var response = instance.WSGetPolicy(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIWSPolicyGetPolicyResponseData> (response, "response is BackofficeModelAPIWSPolicyGetPolicyResponseData");
        }
        
        /// <summary>
        /// Test WSGetUserAcceptance
        /// </summary>
        [Test]
        public void WSGetUserAcceptanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIWSContactGetUserAcceptanceRequestData oRequest = null;
            //var response = instance.WSGetUserAcceptance(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIWSContactGetUserAcceptanceResponseData> (response, "response is BackofficeModelAPIWSContactGetUserAcceptanceResponseData");
        }
        
        /// <summary>
        /// Test WSRetrivePanelLink
        /// </summary>
        [Test]
        public void WSRetrivePanelLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIWSContactRetrivePanelLinkRequestData oRequest = null;
            //var response = instance.WSRetrivePanelLink(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIWSContactRetrivePanelLinkResponseData> (response, "response is BackofficeModelAPIWSContactRetrivePanelLinkResponseData");
        }
        
        /// <summary>
        /// Test WSUpdateMultipleRequestStatus
        /// </summary>
        [Test]
        public void WSUpdateMultipleRequestStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIWSContactUpdateMultipleRequestStatusRequestData oRequest = null;
            //var response = instance.WSUpdateMultipleRequestStatus(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIWSContactUpdateMultipleRequestStatusResponseData> (response, "response is BackofficeModelAPIWSContactUpdateMultipleRequestStatusResponseData");
        }
        
        /// <summary>
        /// Test WSUpdateRequestStatus
        /// </summary>
        [Test]
        public void WSUpdateRequestStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BackofficeModelAPIWSContactUpdateRequestStatusRequestData oRequest = null;
            //var response = instance.WSUpdateRequestStatus(oRequest);
            //Assert.IsInstanceOf<BackofficeModelAPIWSContactUpdateRequestStatusResponseData> (response, "response is BackofficeModelAPIWSContactUpdateRequestStatusResponseData");
        }
        
    }

}
