/* 
 * Tracko
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.trackoApiClient
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface INewsletterApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>BackofficeModelAPINewsletterGetNewslettersResponseData</returns>
        BackofficeModelAPINewsletterGetNewslettersResponseData NewsletterGetNewsletters (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>ApiResponse of BackofficeModelAPINewsletterGetNewslettersResponseData</returns>
        ApiResponse<BackofficeModelAPINewsletterGetNewslettersResponseData> NewsletterGetNewslettersWithHttpInfo (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>BackofficeModelAPINewsletterSaveNewsletterResponseData</returns>
        BackofficeModelAPINewsletterSaveNewsletterResponseData NewsletterSaveNewsletters (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>ApiResponse of BackofficeModelAPINewsletterSaveNewsletterResponseData</returns>
        ApiResponse<BackofficeModelAPINewsletterSaveNewsletterResponseData> NewsletterSaveNewslettersWithHttpInfo (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of BackofficeModelAPINewsletterGetNewslettersResponseData</returns>
        System.Threading.Tasks.Task<BackofficeModelAPINewsletterGetNewslettersResponseData> NewsletterGetNewslettersAsync (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of ApiResponse (BackofficeModelAPINewsletterGetNewslettersResponseData)</returns>
        System.Threading.Tasks.Task<ApiResponse<BackofficeModelAPINewsletterGetNewslettersResponseData>> NewsletterGetNewslettersAsyncWithHttpInfo (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of BackofficeModelAPINewsletterSaveNewsletterResponseData</returns>
        System.Threading.Tasks.Task<BackofficeModelAPINewsletterSaveNewsletterResponseData> NewsletterSaveNewslettersAsync (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of ApiResponse (BackofficeModelAPINewsletterSaveNewsletterResponseData)</returns>
        System.Threading.Tasks.Task<ApiResponse<BackofficeModelAPINewsletterSaveNewsletterResponseData>> NewsletterSaveNewslettersAsyncWithHttpInfo (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class NewsletterApi : INewsletterApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="NewsletterApi"/> class.
        /// </summary>
        /// <returns></returns>
        public NewsletterApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NewsletterApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public NewsletterApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>BackofficeModelAPINewsletterGetNewslettersResponseData</returns>
        public BackofficeModelAPINewsletterGetNewslettersResponseData NewsletterGetNewsletters (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest)
        {
             ApiResponse<BackofficeModelAPINewsletterGetNewslettersResponseData> localVarResponse = NewsletterGetNewslettersWithHttpInfo(oRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>ApiResponse of BackofficeModelAPINewsletterGetNewslettersResponseData</returns>
        public ApiResponse< BackofficeModelAPINewsletterGetNewslettersResponseData > NewsletterGetNewslettersWithHttpInfo (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest)
        {
            // verify the required parameter 'oRequest' is set
            if (oRequest == null)
                throw new ApiException(400, "Missing required parameter 'oRequest' when calling NewsletterApi->NewsletterGetNewsletters");

            var localVarPath = "/api/Newsletter/GetNewsletters";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (oRequest != null && oRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(oRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = oRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NewsletterGetNewsletters", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BackofficeModelAPINewsletterGetNewslettersResponseData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BackofficeModelAPINewsletterGetNewslettersResponseData) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BackofficeModelAPINewsletterGetNewslettersResponseData)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of BackofficeModelAPINewsletterGetNewslettersResponseData</returns>
        public async System.Threading.Tasks.Task<BackofficeModelAPINewsletterGetNewslettersResponseData> NewsletterGetNewslettersAsync (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest)
        {
             ApiResponse<BackofficeModelAPINewsletterGetNewslettersResponseData> localVarResponse = await NewsletterGetNewslettersAsyncWithHttpInfo(oRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of ApiResponse (BackofficeModelAPINewsletterGetNewslettersResponseData)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BackofficeModelAPINewsletterGetNewslettersResponseData>> NewsletterGetNewslettersAsyncWithHttpInfo (BackofficeModelAPINewsletterGetNewslettersRequestData oRequest)
        {
            // verify the required parameter 'oRequest' is set
            if (oRequest == null)
                throw new ApiException(400, "Missing required parameter 'oRequest' when calling NewsletterApi->NewsletterGetNewsletters");

            var localVarPath = "/api/Newsletter/GetNewsletters";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (oRequest != null && oRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(oRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = oRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NewsletterGetNewsletters", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BackofficeModelAPINewsletterGetNewslettersResponseData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BackofficeModelAPINewsletterGetNewslettersResponseData) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BackofficeModelAPINewsletterGetNewslettersResponseData)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>BackofficeModelAPINewsletterSaveNewsletterResponseData</returns>
        public BackofficeModelAPINewsletterSaveNewsletterResponseData NewsletterSaveNewsletters (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest)
        {
             ApiResponse<BackofficeModelAPINewsletterSaveNewsletterResponseData> localVarResponse = NewsletterSaveNewslettersWithHttpInfo(oRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>ApiResponse of BackofficeModelAPINewsletterSaveNewsletterResponseData</returns>
        public ApiResponse< BackofficeModelAPINewsletterSaveNewsletterResponseData > NewsletterSaveNewslettersWithHttpInfo (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest)
        {
            // verify the required parameter 'oRequest' is set
            if (oRequest == null)
                throw new ApiException(400, "Missing required parameter 'oRequest' when calling NewsletterApi->NewsletterSaveNewsletters");

            var localVarPath = "/api/Newsletter/SaveNewsletters";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (oRequest != null && oRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(oRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = oRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NewsletterSaveNewsletters", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BackofficeModelAPINewsletterSaveNewsletterResponseData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BackofficeModelAPINewsletterSaveNewsletterResponseData) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BackofficeModelAPINewsletterSaveNewsletterResponseData)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of BackofficeModelAPINewsletterSaveNewsletterResponseData</returns>
        public async System.Threading.Tasks.Task<BackofficeModelAPINewsletterSaveNewsletterResponseData> NewsletterSaveNewslettersAsync (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest)
        {
             ApiResponse<BackofficeModelAPINewsletterSaveNewsletterResponseData> localVarResponse = await NewsletterSaveNewslettersAsyncWithHttpInfo(oRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="oRequest"></param>
        /// <returns>Task of ApiResponse (BackofficeModelAPINewsletterSaveNewsletterResponseData)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<BackofficeModelAPINewsletterSaveNewsletterResponseData>> NewsletterSaveNewslettersAsyncWithHttpInfo (BackofficeModelAPINewsletterSaveNewsletterRequestData oRequest)
        {
            // verify the required parameter 'oRequest' is set
            if (oRequest == null)
                throw new ApiException(400, "Missing required parameter 'oRequest' when calling NewsletterApi->NewsletterSaveNewsletters");

            var localVarPath = "/api/Newsletter/SaveNewsletters";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (oRequest != null && oRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(oRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = oRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("NewsletterSaveNewsletters", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<BackofficeModelAPINewsletterSaveNewsletterResponseData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (BackofficeModelAPINewsletterSaveNewsletterResponseData) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(BackofficeModelAPINewsletterSaveNewsletterResponseData)));
        }

    }
}
